CREATE DATABASE eweather; 

CREATE TABLE CITY (id INTEGER NOT NULL, NAME VARCHAR(255) NOT NULL, VISIBILITY INTEGER NOT NULL, clouds_id INTEGER UNIQUE, coord_id INTEGER UNIQUE, main_id INTEGER UNIQUE, sys_id INTEGER UNIQUE, wind_id INTEGER UNIQUE, PRIMARY KEY (id));
CREATE TABLE COORD (ID INTEGER NOT NULL, LAT FLOAT NOT NULL, LON FLOAT NOT NULL, PRIMARY KEY (ID));
CREATE TABLE SYS (id INTEGER NOT NULL, country VARCHAR(255) NOT NULL, MESSAGE FLOAT NOT NULL, SUNRISE INTEGER NOT NULL, SUNSET INTEGER NOT NULL, TYPE INTEGER NOT NULL, PRIMARY KEY (id));
CREATE TABLE WEATHER (id INTEGER NOT NULL, description VARCHAR(255) NOT NULL, icon VARCHAR(255) NOT NULL, main VARCHAR(255) NOT NULL, city_id INTEGER, PRIMARY KEY (id));
CREATE TABLE MAIN (ID INTEGER NOT NULL, HUMIDITY INTEGER NOT NULL, PRESSURE INTEGER NOT NULL, TEMP FLOAT NOT NULL, TEMP_MAX INTEGER NOT NULL, TEMP_MIN INTEGER NOT NULL, PRIMARY KEY (ID));
CREATE TABLE WIND (ID INTEGER NOT NULL, DEG INTEGER NOT NULL, GUST FLOAT NOT NULL, SPEED FLOAT NOT NULL, PRIMARY KEY (ID));
CREATE TABLE CLOUDS (ID INTEGER NOT NULL, ALL_ INTEGER NOT NULL, PRIMARY KEY (ID));
ALTER TABLE CITY ADD CONSTRAINT FK_CITY_coord_id FOREIGN KEY (coord_id) REFERENCES COORD (ID);
ALTER TABLE CITY ADD CONSTRAINT FK_CITY_wind_id FOREIGN KEY (wind_id) REFERENCES WIND (ID);
ALTER TABLE CITY ADD CONSTRAINT FK_CITY_clouds_id FOREIGN KEY (clouds_id) REFERENCES CLOUDS (ID);
ALTER TABLE CITY ADD CONSTRAINT FK_CITY_main_id FOREIGN KEY (main_id) REFERENCES MAIN (ID);
ALTER TABLE CITY ADD CONSTRAINT FK_CITY_sys_id FOREIGN KEY (sys_id) REFERENCES SYS (id);
ALTER TABLE WEATHER ADD CONSTRAINT FK_WEATHER_city_id FOREIGN KEY (city_id) REFERENCES CITY (id);
CREATE SEQUENCE SEQ_GEN_SEQUENCE INCREMENT BY 50 START WITH 50;
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN_TABLE', 0);
